version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soon-my-room-api-prod
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: always
    networks:
      - soon-my-room-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

networks:
  soon-my-room-network:
    driver: bridge
