version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soon-my-room-api-prod
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SUPABASE_ENDPOINT=${SUPABASE_ENDPOINT}
      - SUPABASE_REGION=${SUPABASE_REGION}
      - SUPABASE_ACCESS_KEY=${SUPABASE_ACCESS_KEY}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
      - SUPABASE_BUCKET_PROFILES=${SUPABASE_BUCKET_PROFILES:-user-profiles}
      - SUPABASE_BUCKET_POSTS=${SUPABASE_BUCKET_POSTS:-post-images}
      - SUPABASE_BUCKET_PRODUCTS=${SUPABASE_BUCKET_PRODUCTS:-product-images}
      - SUPABASE_BUCKET_DEFAULT=${SUPABASE_BUCKET_DEFAULT:-default}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-https://soon-my-room.com,https://www.soon-my-room.com}
    volumes:
      - ./logs:/app/logs
    restart: always
    networks:
      - soon-my-room-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  soon-my-room-network:
    driver: bridge