version: "3.8"

services:
  app:
    image: soon-my-room-api:dev-latest
    container_name: soon-my-room-api-dev
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - soon-my-room-network

networks:
  soon-my-room-network:
    driver: bridge
