version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${SERVER_PORT:-8000}
    container_name: soon-my-room-api-dev
    ports:
      - "${SERVER_PORT:-8000}:${SERVER_PORT:-8000}"
    env_file:
      - .env
    environment:
      - SERVER_PORT=${SERVER_PORT:-8000}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - soon-my-room-network

networks:
  soon-my-room-network:
    driver: bridge
