name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 디버깅: 시크릿 존재 여부 확인
      - name: Check if secrets exist
        run: |
          if [ -n "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
          echo "DOCKER_HUB_USERNAME exists"
          else
          echo "DOCKER_HUB_USERNAME is empty or not set"
          fi
          
          if [ -n "${{ secrets.DOCKER_HUB_TOKEN }}" ]; then
          echo "DOCKER_HUB_TOKEN exists (value is hidden)"
          else
          echo "DOCKER_HUB_TOKEN is empty or not set"
          fi

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Apply Spotless
        run: ./gradlew spotlessApply

      - name: Run tests
        run: ./gradlew test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/soon-my-room-api:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 배포 스크립트 실행
            ~/workspace/soon_my_room_deploy/soon_my_room_api_deploy.sh ${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}