name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Create .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "AWS_S3_REGION=${{ secrets.AWS_S3_REGION }}" >> .env
          echo "AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }}" >> .env
          echo "AWS_S3_SECRET_KEY=${{ secrets.AWS_S3_SECRET_KEY }}" >> .env
          echo "AWS_S3_BUCKET_PROFILES=${{ secrets.AWS_S3_BUCKET_PROFILES }}" >> .env
          echo "AWS_S3_BUCKET_POSTS=${{ secrets.AWS_S3_BUCKET_POSTS }}" >> .env
          echo "AWS_S3_BUCKET_PRODUCTS=${{ secrets.AWS_S3_BUCKET_PRODUCTS }}" >> .env
          echo "AWS_S3_BUCKET_DEFAULT=${{ secrets.AWS_S3_BUCKET_DEFAULT }}" >> .env

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Apply Spotless
        run: ./gradlew spotlessApply

      - name: Run tests
        run: ./gradlew test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/soon-my-room-api:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 배포 스크립트 실행
            ~/workspace/soon_my_room_deploy/soon_my_room_api_deploy.sh ${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}